version: "3"
services:
  sbt:
    image: sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.1_3.2.0
    working_dir: ${PWD}
    volumes:
      - ../:${PWD}
      - ../:/root
    ports:
      - 8080:8080
    entrypoint:
      - sbt
      - run
