addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"  % "0.11.0")
addSbtPlugin("au.com.onegeek"           %% "sbt-dotenv"    % "2.1.233")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.4.2")
addSbtPlugin("dev.guardrail"             % "sbt-guardrail" % "0.75.2")
